version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - "54321:5432"
volumes:
  postgres:
